GET http://localhost:3000

###

GET http://localhost:3000/books

###
GET http://localhost:3000/books/609a850cf9e4747ef299c853
###

POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Super livre",
  "description": "Description du livre",
  "image": "https://AFRIQUE-map-clic.png",
  "author": "Angelina Aludo",
  "stars": 5,
  "price": 10.2
}

###

PATCH http://localhost:3000/books/609a8b38ecaf8b8aa776d70a
Content-Type: application/json

{
  "title": "Un nouveau titre 2 !",
  "description": "ça marche ??"
}

###
DELETE http://localhost:3000/books/609a87137fdc501fd1b95669